import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { Activity, ArrowLeft, Cable, Globe2, KeyRound, RefreshCw, ScrollText, Settings2, Shield, Users, Webhook } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { AdminResourceKey } from "@unimailbox/contracts";
import { ErrorState, LoadingState, SuccessNote } from "../../components/Status";
import { useAppForm } from "../../lib/form/app-form";
import { adminMutationOptions, adminQueryOptions, auditEventsQueryOptions, providerSyncMutationOptions, saveSettingsMutationOptions, saveSignatureMutationOptions, signatureQueryOptions } from "./api";

const navigation: Array<[AdminResourceKey, React.ComponentType<{ className?: string }>]> = [
  ["users", Users], ["roles", Shield], ["domains", Globe2], ["signatures", ScrollText], ["settings", Settings2], ["provider-connections", Cable], ["webhook-events", Webhook], ["audit-events", KeyRound], ["analytics", Activity],
];
const creatable = new Set<AdminResourceKey>(["users", "roles", "domains", "provider-connections"]);
const manageable = new Set<AdminResourceKey>(["users", "roles", "domains", "provider-connections", "webhook-events"]);
const columnKeys = new Set(["id", "email", "display_name", "status", "created_at", "roles", "name", "description", "is_system", "permissions", "outbound_connection_id", "provider_key", "provider_label", "label", "event_type", "provider_message_id", "message_id", "recipient", "mapped_status", "reason", "action", "resource_type", "resource_id", "request_id", "metadata_json", "active_users", "active_mailboxes", "received_messages", "sent_messages", "failed_jobs", "failed_webhooks"]);

function splitValues(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }

function DataTable({ data }: { data: unknown }) {
  const { t } = useTranslation("admin");
  const rows = Array.isArray(data) ? data : data ? [data] : [];
  const columns = [...new Set(rows.flatMap((row) => row && typeof row === "object" ? Object.keys(row as object).filter((key) => columnKeys.has(key)) : []))].slice(0, 8);
  if (!rows.length) return <div className="empty-admin"><strong>{t("states.emptyTitle")}</strong><p>{t("states.emptyBody")}</p></div>;
  const value = (key: string, raw: unknown) => {
    if (key === "reason" || key === "metadata_json") return t("values.empty");
    if (raw === null || raw === undefined || raw === "") return t("values.empty");
    if (typeof raw === "boolean") return t(raw ? "values.true" : "values.false");
    if (typeof raw === "string" && ["active", "suspended", "disabled", "reject", "store"].includes(raw)) return t(`values.${raw}`);
    return <bdi dir="ltr">{String(raw)}</bdi>;
  };
  return <div className="data-table-wrap"><table className="data-table"><thead><tr>{columns.map((column) => <th key={column}>{t(`columns.${column}`)}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String((row as { id?: unknown }).id ?? index)}>{columns.map((column) => <td key={column}>{value(column, (row as Record<string, unknown>)[column])}</td>)}</tr>)}</tbody></table></div>;
}

type CreateValues = { displayName: string; email: string; password: string; roleIds: string; name: string; description: string; permissions: string; label: string; apiKey: string; webhookSecret: string };
function CreatePanel({ resource }: { resource: AdminResourceKey }) {
  const { t } = useTranslation("admin"); const client = useQueryClient(); const mutation = useMutation(adminMutationOptions(client).create);
  const form = useAppForm({ defaultValues: { displayName: "", email: "", password: "", roleIds: "", name: "", description: "", permissions: "", label: "", apiKey: "", webhookSecret: "" } as CreateValues, onSubmit: async ({ value }) => {
    const input = resource === "users" ? { resource, email: value.email, displayName: value.displayName, password: value.password, roleIds: splitValues(value.roleIds) } : resource === "roles" ? { resource, name: value.name, description: value.description, permissions: splitValues(value.permissions) } : resource === "domains" ? { resource, name: value.name } : { resource, providerKey: "brevo", label: value.label, apiKey: value.apiKey, webhookSecret: value.webhookSecret };
    await mutation.mutateAsync(input); form.reset();
  }});
  if (!creatable.has(resource)) return null;
  const fields: Array<[keyof CreateValues, string, string?]> = resource === "users" ? [["displayName", "displayName"], ["email", "email", "email"], ["password", "password", "password"], ["roleIds", "roleIds"]] : resource === "roles" ? [["name", "name"], ["description", "description"], ["permissions", "permissions"]] : resource === "domains" ? [["name", "name"]] : [["label", "label"], ["apiKey", "apiKey", "password"], ["webhookSecret", "webhookSecret", "password"]];
  return <details className="create-panel"><summary>{t("actions.add", { resource: t(`navigation.${resource}`) })}</summary><form onSubmit={(event) => { event.preventDefault(); void form.handleSubmit(); }}>{fields.map(([name, label, type]) => <form.AppField key={name} name={name}>{(field) => type === "password" ? <field.PasswordField autoComplete="new-password" label={`admin:fields.${label}`} /> : <field.TextField autoComplete={name === "email" ? "email" : undefined} inputMode={name === "email" ? "email" : undefined} label={`admin:fields.${label}`} />}</form.AppField>)}{mutation.error ? <ErrorState error={mutation.error} /> : null}<form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>{([canSubmit, isSubmitting]) => <button className="button primary" disabled={mutation.isPending || !canSubmit || isSubmitting}>{t("actions.create")}</button>}</form.Subscribe></form></details>;
}

type ManageValues = { id: string; action: "update" | "delete"; displayName: string; status: "" | "active" | "suspended" | "disabled"; roleIds: string; description: string; permissions: string; outboundConnectionId: string; apiKey: string; webhookSecret: string };
function ManagePanel({ resource }: { resource: AdminResourceKey }) {
  const { t } = useTranslation("admin"); const client = useQueryClient(); const mutations = adminMutationOptions(client); const update = useMutation(mutations.update); const remove = useMutation(mutations.delete);
  const form = useAppForm({ defaultValues: { id: "", action: "update", displayName: "", status: "", roleIds: "", description: "", permissions: "", outboundConnectionId: "", apiKey: "", webhookSecret: "" } as ManageValues, onSubmit: async ({ value }) => {
    if (resource === "webhook-events" || value.action === "delete") await remove.mutateAsync({ resource, id: value.id });
    else if (resource === "users") await update.mutateAsync({ resource, id: value.id, ...(value.displayName ? { displayName: value.displayName } : {}), ...(value.status ? { status: value.status } : {}), ...(value.roleIds ? { roleIds: splitValues(value.roleIds) } : {}) });
    else if (resource === "roles") await update.mutateAsync({ resource, id: value.id, description: value.description, permissions: splitValues(value.permissions) });
    else if (resource === "domains") await update.mutateAsync({ resource, id: value.id, ...(value.status ? { status: value.status as "active" | "disabled" } : {}), ...(value.outboundConnectionId ? { outboundConnectionId: value.outboundConnectionId } : {}) });
    else if (resource === "provider-connections") await update.mutateAsync({ resource, id: value.id, ...(value.status ? { status: value.status as "active" | "disabled" } : {}), ...(value.apiKey ? { apiKey: value.apiKey } : {}), ...(value.webhookSecret ? { webhookSecret: value.webhookSecret } : {}) });
    form.reset();
  }});
  if (!manageable.has(resource)) return null;
  const error = update.error ?? remove.error;
  return <details className="create-panel"><summary>{t("actions.manage", { resource: t(`navigation.${resource}`) })}</summary><form onSubmit={(event) => { event.preventDefault(); void form.handleSubmit(); }}><form.Field name="id">{(field) => <label className="field" htmlFor={field.name}><span>{t("fields.id")}</span><input id={field.name} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} value={field.state.value} /></label>}</form.Field>{resource !== "provider-connections" && resource !== "webhook-events" ? <form.Field name="action">{(field) => <label className="field" htmlFor={field.name}><span>{t("fields.action")}</span><select id={field.name} onChange={(event) => field.handleChange(event.target.value as "update" | "delete")} value={field.state.value}><option value="update">{t("values.update")}</option><option value="delete">{t("values.delete")}</option></select></label>}</form.Field> : null}{resource === "users" ? <SimpleManageFields form={form} fields={["displayName", "status", "roleIds"]} /> : resource === "roles" ? <SimpleManageFields form={form} fields={["description", "permissions"]} /> : resource === "domains" ? <SimpleManageFields form={form} fields={["status", "outboundConnectionId"]} /> : resource === "provider-connections" ? <SimpleManageFields form={form} fields={["status", "apiKey", "webhookSecret"]} /> : null}{error ? <ErrorState error={error} /> : null}<button className="button primary" disabled={update.isPending || remove.isPending || !form.state.canSubmit}>{resource === "webhook-events" ? t("actions.delete") : t("actions.update")}</button></form></details>;
}

function SimpleManageFields({ form, fields }: { form: any; fields: Array<keyof ManageValues> }) {
  const { t } = useTranslation("admin"); return <>{fields.map((name) => <form.Field key={name} name={name}>{(field: any) => name === "status" ? <label className="field" htmlFor={field.name}><span>{t("fields.status")}</span><select id={field.name} onChange={(event) => field.handleChange(event.target.value as ManageValues["status"])} value={field.state.value}><option value="">{t("values.unchanged")}</option><option value="active">{t("values.active")}</option><option value="suspended">{t("values.suspended")}</option><option value="disabled">{t("values.disabled")}</option></select></label> : <label className="field" htmlFor={field.name}><span>{t(`fields.${name}`)}</span><input id={field.name} onBlur={field.handleBlur} onChange={(event) => field.handleChange(event.target.value)} type={name === "apiKey" || name === "webhookSecret" ? "password" : "text"} value={field.state.value} /></label>}</form.Field>)}</>;
}

function SignatureEditor({ domains }: { domains: Array<{ id: string; name: string }> }) {
  const { t } = useTranslation("admin"); const client = useQueryClient(); const [domainId, setDomainId] = useState(""); const signature = useQuery(signatureQueryOptions(domainId)); const save = useMutation(saveSignatureMutationOptions(client, domainId));
  const form = useAppForm({ defaultValues: { html: "", text: "", enabled: false }, onSubmit: async ({ value }) => { await save.mutateAsync(value); } });
  useEffect(() => { if (!domainId && domains[0]) setDomainId(domains[0].id); }, [domainId, domains]);
  useEffect(() => { if (signature.data) form.reset({ html: signature.data.html_content, text: signature.data.text_content, enabled: Boolean(signature.data.is_enabled) }); }, [form, signature.data]);
  return <section className="admin-editor"><h2>{t("navigation.signatures")}</h2><label className="field"><span>{t("fields.domain")}</span><select onChange={(event) => setDomainId(event.target.value)} value={domainId}>{domains.map((domain) => <option key={domain.id} value={domain.id}>{domain.name}</option>)}</select></label>{signature.isLoading ? <LoadingState /> : null}<form onSubmit={(event) => { event.preventDefault(); void form.handleSubmit(); }}><form.Field name="text">{(field) => <label className="field" htmlFor={field.name}><span>{t("fields.plainSignature")}</span><textarea id={field.name} onChange={(event) => field.handleChange(event.target.value)} value={field.state.value} /></label>}</form.Field><form.Field name="html">{(field) => <label className="field" htmlFor={field.name}><span>{t("fields.htmlSignature")}</span><textarea id={field.name} onChange={(event) => field.handleChange(event.target.value)} value={field.state.value} /></label>}</form.Field><form.Field name="enabled">{(field) => <label className="check-field"><input checked={field.state.value} onChange={(event) => field.handleChange(event.target.checked)} type="checkbox" />{t("fields.enabled")}</label>}</form.Field>{save.error ? <ErrorState error={save.error} /> : null}{save.isSuccess ? <SuccessNote>{t("states.signatureSaved")}</SuccessNote> : null}<button className="button primary" disabled={save.isPending || !domainId}>{t("actions.saveSignature")}</button></form></section>;
}

function SettingsEditor({ settings }: { settings: Record<string, unknown> }) {
  const { t } = useTranslation("admin"); const client = useQueryClient(); const save = useMutation(saveSettingsMutationOptions(client)); const form = useAppForm({ defaultValues: { site_title: "", registration_enabled: false, invite_required: false, inbound_enabled: false, outbound_enabled: false, unknown_recipient_policy: "reject" as "reject" | "store", max_mailboxes_per_user: 10, max_attachments_per_message: 20, max_attachment_bytes: 26214400 }, onSubmit: async ({ value }) => { await save.mutateAsync({ ...value, registration_enabled: Number(value.registration_enabled), invite_required: Number(value.invite_required), inbound_enabled: Number(value.inbound_enabled), outbound_enabled: Number(value.outbound_enabled) }); } });
  useEffect(() => { form.reset({ site_title: String(settings.site_title ?? "UniMailbox"), registration_enabled: Boolean(settings.registration_enabled), invite_required: Boolean(settings.invite_required), inbound_enabled: Boolean(settings.inbound_enabled), outbound_enabled: Boolean(settings.outbound_enabled), unknown_recipient_policy: settings.unknown_recipient_policy === "store" ? "store" : "reject", max_mailboxes_per_user: Number(settings.max_mailboxes_per_user ?? 10), max_attachments_per_message: Number(settings.max_attachments_per_message ?? 20), max_attachment_bytes: Number(settings.max_attachment_bytes ?? 26214400) }); }, [form, settings]);
  const textFields = [["site_title", "siteTitle"], ["max_mailboxes_per_user", "mailboxesPerUser"], ["max_attachments_per_message", "attachmentsPerMessage"], ["max_attachment_bytes", "attachmentBytes"]] as const;
  const checks = [["registration_enabled", "registrationEnabled"], ["invite_required", "inviteRequired"], ["inbound_enabled", "inboundEnabled"], ["outbound_enabled", "outboundEnabled"]] as const;
  return <section className="admin-editor"><h2>{t("navigation.settings")}</h2><form onSubmit={(event) => { event.preventDefault(); void form.handleSubmit(); }}>{textFields.map(([name, label]) => <form.Field key={name} name={name}>{(field) => <label className="field" htmlFor={field.name}><span>{t(`fields.${label}`)}</span><input id={field.name} onChange={(event) => field.handleChange(name === "site_title" ? event.target.value : Number(event.target.value))} type={name === "site_title" ? "text" : "number"} value={field.state.value} /></label>}</form.Field>)}<form.Field name="unknown_recipient_policy">{(field) => <label className="field" htmlFor={field.name}><span>{t("fields.unknownRecipientPolicy")}</span><select id={field.name} onChange={(event) => field.handleChange(event.target.value as "reject" | "store")} value={field.state.value}><option value="reject">{t("values.reject")}</option><option value="store">{t("values.store")}</option></select></label>}</form.Field>{checks.map(([name, label]) => <form.Field key={name} name={name}>{(field) => <label className="check-field"><input checked={field.state.value} onChange={(event) => field.handleChange(event.target.checked)} type="checkbox" />{t(`fields.${label}`)}</label>}</form.Field>)}{save.error ? <ErrorState error={save.error} /> : null}{save.isSuccess ? <SuccessNote>{t("states.settingsSaved")}</SuccessNote> : null}<button className="button primary" disabled={save.isPending}>{t("actions.saveSettings")}</button></form></section>;
}

export function AdminPage({ resource }: { resource: AdminResourceKey }) {
  const { t } = useTranslation("admin"); const client = useQueryClient(); const [auditSearch, setAuditSearch] = useState(""); const query = useQuery((resource === "audit-events" ? auditEventsQueryOptions(auditSearch) : adminQueryOptions(resource)) as any); const sync = useMutation(providerSyncMutationOptions(client));
  return <div className="admin-app"><aside className="admin-sidebar"><Link className="wordmark compact" to="/inbox"><span>CM</span> UniMailbox</Link><div className="admin-rail-title">{t("controlPlane")}</div><nav>{navigation.map(([id, Icon]) => <Link aria-current={id === resource ? "page" : undefined} className={id === resource ? "active" : ""} key={id} to={`/admin/${id}`}><Icon aria-hidden="true" />{t(`navigation.${id}`)}</Link>)}</nav><Link className="back-link" to="/inbox"><ArrowLeft aria-hidden="true" className="directional-icon" />{t("backToMail")}</Link></aside><main className="admin-main"><header><div><div className="section-kicker">{t("title")}</div><h1>{t(`navigation.${resource}`)}</h1></div>{resource === "provider-connections" ? <button className="button secondary" disabled={sync.isPending} onClick={() => sync.mutate()} type="button"><RefreshCw aria-hidden="true" className={sync.isPending ? "spin" : ""} />{t("actions.reconcile")}</button> : null}</header><section className="admin-surface"><div className="surface-heading"><div><span className="status-pill">{t("live")}</span><strong>{t("registry", { resource: t(`navigation.${resource}`) })}</strong></div><small>{t("audited")}</small></div>{resource === "audit-events" ? <label className="admin-search"><span>{t("search.label")}</span><input onChange={(event) => setAuditSearch(event.target.value)} placeholder={t("search.placeholder")} value={auditSearch} /></label> : null}{sync.isSuccess ? <SuccessNote>{t("states.syncComplete")}</SuccessNote> : null}{query.isLoading ? <LoadingState /> : query.error ? <ErrorState error={query.error} retry={() => void query.refetch()} /> : <><DataTable data={query.data} />{resource === "signatures" ? <SignatureEditor domains={Array.isArray(query.data) ? query.data as unknown as Array<{ id: string; name: string }> : []} /> : null}{resource === "settings" && query.data ? <SettingsEditor settings={query.data as unknown as Record<string, unknown>} /> : null}</>}</section><CreatePanel resource={resource} /><ManagePanel resource={resource} /></main></div>;
}
